name: Doxygen Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repozitorija
        uses: actions/checkout@v3

      - name: Instaliraj Doxygen i Graphviz
        run: sudo apt-get install -y doxygen graphviz

      - name: Generiraj Doxygen dokumentaciju
        run: |
          cd Lab1
          doxygen Doxyfile

      - name: Objavi na GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Lab1/docs/html
